<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TO01</name>
   <tag></tag>
   <elementGuidId>ae011486-8f80-4e79-b504-af836eab3597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21770371-80a4-4214-8546-3b0cb4469cb1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
